name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.5' # Specify the JDK version here
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Static Code Analysis
        run: ./gradlew detekt

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Generate Code Coverage Report
        run: ./gradlew jacocoTestReport

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: app/build/reports/tests/testDebugUnitTest/
